### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by Heimdallr-1**
TIA

### CODE REVIEW

**Comment by RayTrace082** [comment]
>TIA

What does this mean? Is this commit ready to merge?

Additionally, I am pushing a bugfix update soon for 1.18.2, I can either bundle this translation there too, since the lang file is pretty much the same, or you can open another PR targeting the 1.18 branch

**Comment by Heimdallr-1** [comment]
So, like, what does this mean? When I create an PR, I hit the "Create PR" button, which means you gotta merge it.

Moreover, version 1.20.1 is already out, so it's time to port the mod to that version.

**Comment by RayTrace082** [comment]
I was asking if the commit is ready to merge, which I guess is the case, I will manually add the ru_ru file into the 1.18 branch myself, and merge this pull request into 1.19 later
If you'd like to be credited under a different nickname let me know, otherwise I will use your username

And thank you for the translation!

**Comment by Heimdallr-1** [comment]
TIA - **Thanks in advance**

**Comment by Heimdallr-1** [comment]
I'll create a pull request in the 1.18 branch.

**Pull request merged**
